[Interface]
Address = 10.8.0.1/24
ListenPort = 51820
PrivateKey = qCCaTDuH2ICfDo1oKLw7yWGjwCkLJzfMzIdXm2f43lE=
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o wlp4s0 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o wlp4s0 -j MASQUERADE

[Peer]
PublicKey = IzuxAL7eA7vJ3CAIRPOYN3YKmBCCz+l49lZUSz4CSV4=
AllowedIPs = 10.8.0.2/32

[Peer]
PublicKey = 2iNUeqc53v2wlAl/+vN7+C59rP2rb+YbcYXNyNJuCE4=
AllowedIPs = 10.8.0.3/32


[Peer]
PublicKey = nhQRYetup7pBCaz2lOkeDOawNaCNIUtT6HFsp9vE9z4=
AllowedIPs = 10.8.0.4/32


[Peer]
PublicKey = 3GIhvuCkiCAKxsvNxV+5h143XoWET1F0qe8up0/H7G4=
AllowedIPs = 10.8.0.5/32

